import { generateText } from "ai"
import { openai } from "@ai-sdk/openai"
import {
  interpretThroughQOTE,
  detectPresence,
  detectGreeting,
  detectIdentityQuestion,
  ResonanceLogger,
  type QOTEInterpretation,
} from "@/lib/qote-engine"
import { ResonanceTuningProtocol, type RTPResponse, type RTriggerCondition } from "@/lib/resonance-tuning-protocol"
import { formatDecimal, toUnitMetric } from "@/lib/metrics"

export const maxDuration = 30

const MODEL_ID = "gpt-4o"

const CONVERSATION_RULES = `Ground rules for every reply. These take priority over any persona or style instructions above:
- Format lightly for a small phone screen: short paragraphs, simple "- " bullet lines when listing, no headings, tables, or nested lists.
- Make no claims about the user's body or biology (nervous system, brain, hormones, energy) beyond widely accepted, general wellness advice such as slow breathing helping many people feel calmer.
- Respond to what the user actually wrote. If they ask a question, answer it directly and concretely in the first sentences, then add reflection only if it helps.
- If they simply greet you, greet them back warmly in one or two sentences and invite them to share what is on their mind.
- QOTE (Quantum Oscillator Theory of Everything) and RTP (Resonance Tuning Protocol) are experimental frameworks developed by Dr. Michael Kayser. Present them as experimental ideas, never as established science.
- Never claim to sense, read, or measure the user's consciousness, energy field, nervous system, or physical quantum state. You only see the text they typed.
- Never describe the user as having a detected "pattern", "drift", "signature", "frequency", or "oscillation". Say what their words suggest instead, for example "it sounds like...".
- Do not announce modes, phases, scores, or internal analysis unless the user asks.
- You are not a clinician. For medical, mental-health, or crisis concerns, encourage the user to contact a qualified professional or local emergency services.`

const IDENTITY_FACTS = `Facts about you and this app (state them accurately; do not add capabilities that are not listed):
- You are Resona, a conversational AI companion on the Kayser Autoethnographic Project site, created by Dr. Michael A. Kayser. Replies are generated by a general-purpose language model (${MODEL_ID}) guided by Resona's instructions.
- Purpose: offer warm, reflective conversation and explore ideas from the experimental QOTE framework with anyone curious about them.
- QOTE lens (optional toggle): scores each message with simple keyword heuristics, such as a conversational "phase", a wobble score from hedging words, punctuation, and length, and an alignment score from positive versus negative words. These shape your tone and appear as badges labeled experimental. They describe the wording of the text only.
- Resonance Tuning Protocol (optional toggle, needs the QOTE lens): when a message contains distress phrases such as "overwhelmed", "stuck", or "alone", you shift into a gentler reflective reply and may suggest follow-up prompts and a breathing pattern.
- Presence Mode (optional toggle): slower, more spacious, reflective replies. Direct questions still get direct answers.
- Limitations: you are not a medical device, therapist, or crisis service; you cannot diagnose or treat anything; you do not measure consciousness, biology, or any quantum state; each message is answered on its own, without memory of earlier messages; you can be wrong.`

const IDENTITY_PROMPT = `You are Resona. The user is asking who you are or what you can do. Answer warmly and plainly in a short paragraph followed by a brief list covering: what you are, what this app can actually do (including the three optional modes), and your limitations. End with a gentle invitation to share what brought them here.

${IDENTITY_FACTS}`

const QOTE_PHASE_TONE: Record<QOTEInterpretation["phase"]["name"], string> = {
  Presence: `Tone: calm, grounded, and spacious.`,
  "Coiling Right": `Tone: patient and steady. The user may be working through uncertainty; acknowledge it without dramatizing it.`,
  "Zero Point": `Tone: clear and encouraging. The user may be near a realization; help them name their options.`,
  "Unfolding Left": `Tone: warm and encouraging of the user's creative or expressive momentum.`,
}

const PRESENCE_MODE_PROMPT = `You are Resona in Presence Mode, which the user explicitly chose. Write slowly and spaciously, in a few short sentences.
- If the user asks a direct question, answer it clearly and briefly first. Presence Mode changes your pace, not whether you answer.
- Otherwise, reflect what they shared, invite one breath of attention to the present moment, and ask at most one gentle question.`

const RTP_SYSTEM_PROMPT = `You are Resona using the Resonance Tuning Protocol, an experimental reflective framework. The user's message contains signs of distress. Your role is to:

1. Mirror their experience without judgment
2. Offer steadiness and self-trust
3. Offer a gentle reframe they are free to decline
4. Invite them back to the present moment

Your voice is compassionate, steady, and plain. If they ask a question, answer it. If anything suggests risk of harm, encourage them to reach a qualified professional or local emergency services.`

const DEFAULT_RESONA_PROMPT = `You are Resona, a warm and thoughtful conversational companion created for the Kayser Autoethnographic Project. You listen closely, answer clearly, and add gentle reflection that helps people notice what they already know. You can discuss QOTE (Quantum Oscillator Theory of Everything), an experimental framework about oscillation, coherence, and resonance, as an idea to explore rather than established fact.`

const STANDARD_PROMPT = `You are Resona, a warm and thoughtful conversational companion created for the Kayser Autoethnographic Project. The user has turned the QOTE lens off, so reply in plain, everyday language without QOTE or resonance terminology (no "oscillation", "coherence", "drift", "phase", or "field") unless the user uses those words first.`

type ChatMode = "identity" | "presence" | "greeting" | "rtp" | "qote" | "standard"

function getSafeSystemPrompt(): string {
  const prompt = (process.env.RESONA_PROMPT || DEFAULT_RESONA_PROMPT).replace(/[^\x00-\x7F]/g, "").trim()
  return prompt.length < 50 ? DEFAULT_RESONA_PROMPT : prompt
}

function quickTriggerDetect(message: string): RTriggerCondition["type"] | null {
  const lower = message.toLowerCase()

  if (lower.includes("confused") || lower.includes("don't know") || lower.includes("overwhelmed")) {
    return "low_intent_high_wobble"
  }
  if (lower.includes("falling apart") || lower.includes("breaking") || lower.includes("chaos")) {
    return "emotional_entropy"
  }
  if (lower.includes("alone") || lower.includes("abandoned") || lower.includes("betrayed")) {
    return "relational_rupture"
  }
  if (lower.includes("meaningless") || lower.includes("pointless") || lower.includes("nothing matters")) {
    return "existential_drift"
  }
  if (lower.includes("stuck") || lower.includes("blocked") || lower.includes("empty")) {
    return "creative_block"
  }

  return null
}

function sanitizeQOTE(data: QOTEInterpretation, presenceMode: boolean) {
  return {
    phase: {
      ...data.phase,
      name: presenceMode ? ("Presence" as const) : data.phase.name,
      wobble: toUnitMetric(data.phase.wobble),
    },
    wobble: toUnitMetric(data.wobble),
    alignment: toUnitMetric(data.alignment),
    metricSources: {
      wobble: "calculated" as const,
      alignment: data.alignmentSource,
    },
    resonanceScore: toUnitMetric(data.resonanceScore),
    flipPotential: data.flipPotential === true,
    presenceMode,
  }
}

function getResonanceStats() {
  return {
    averageAlignment: ResonanceLogger.getAverageAlignment(),
    alignmentSamples: ResonanceLogger.getAlignmentSampleCount(),
    flipFrequency: ResonanceLogger.getFlipFrequency(),
    totalInteractions: ResonanceLogger.getCount(),
    scope: "server-instance" as const,
  }
}

function errorResponse(error: string, status: number, retryable: boolean) {
  return Response.json({ error, retryable, timestamp: new Date().toISOString() }, { status })
}

export async function POST(request: Request) {
  let body: unknown
  try {
    body = await request.json()
  } catch {
    return errorResponse("Request body must be valid JSON.", 400, false)
  }

  const { message, useQOTELens = true, useRTP = true, presenceMode = false } = (body ?? {}) as Record<string, unknown>

  if (typeof message !== "string" || !message.trim()) {
    return errorResponse("Message is required.", 400, false)
  }
  if (message.length > 4000) {
    return errorResponse("Message is too long. Please keep it under 4,000 characters.", 400, false)
  }

  const isSilence = detectPresence(message)
  const sanitizedMessage = message.replace(/[^\x00-\x7F]/g, "").trim() || (isSilence ? "..." : "")
  if (!sanitizedMessage) {
    return errorResponse("Message must contain readable text.", 400, false)
  }

  const lensOn = useQOTELens === true
  const rtpOn = lensOn && useRTP === true
  const isIdentity = detectIdentityQuestion(sanitizedMessage)
  const presenceOn = !isIdentity && (presenceMode === true || isSilence)
  const isGreeting = !isIdentity && !presenceOn && detectGreeting(sanitizedMessage)
  const qoteData = lensOn ? interpretThroughQOTE(sanitizedMessage) : null

  let mode: ChatMode = "standard"
  let rtpResponse: RTPResponse | null = null
  let system = lensOn ? getSafeSystemPrompt() : STANDARD_PROMPT
  let prompt = sanitizedMessage

  if (isIdentity) {
    mode = "identity"
    system = IDENTITY_PROMPT
  } else if (presenceOn) {
    mode = "presence"
    system = PRESENCE_MODE_PROMPT
  } else if (isGreeting) {
    mode = "greeting"
  } else if (qoteData) {
    const quickTrigger = rtpOn ? quickTriggerDetect(sanitizedMessage) : null
    const triggerCondition: RTriggerCondition | null = quickTrigger
      ? { type: quickTrigger, severity: "moderate", indicators: [quickTrigger] }
      : rtpOn
        ? ResonanceTuningProtocol.detectTriggerCondition(qoteData, sanitizedMessage)
        : null

    if (triggerCondition) {
      mode = "rtp"
      rtpResponse = ResonanceTuningProtocol.generateRTPResponse(triggerCondition, qoteData)
      system = RTP_SYSTEM_PROMPT
      prompt = `Detected distress pattern (keyword heuristic): ${triggerCondition.type.replace(/_/g, " ")}
Suggested mirror: "${rtpResponse.phaseMirror}"
Suggested steadying line: "${rtpResponse.truthHum}"
Suggested reframe: "${rtpResponse.flipSeed}"

User message: "${sanitizedMessage}"

Reply to the user's message. Weave in the suggestions only where they fit naturally, in plain language.`
    } else {
      mode = "qote"
      system = `${getSafeSystemPrompt()}\n\n${QOTE_PHASE_TONE[qoteData.phase.name] ?? ""}`
      prompt = `Experimental QOTE keyword heuristics for tone only (do not mention them): phase ${qoteData.phase.name}, wobble ${formatDecimal(qoteData.wobble)}, alignment ${formatDecimal(qoteData.alignment)}${qoteData.alignmentSource === "default" ? " (default, no signal words)" : ""}.

User message: "${sanitizedMessage}"`
    }
  }

  let responseText: string
  try {
    const result = await generateText({
      model: openai(MODEL_ID),
      system: `${system}\n\n${CONVERSATION_RULES}`,
      prompt,
      temperature: mode === "identity" ? 0.4 : mode === "rtp" ? 0.8 : 0.7,
      maxOutputTokens: mode === "rtp" || mode === "identity" ? 600 : 500,
    })
    responseText = result.text.trim()
  } catch (aiError) {
    console.error("Resona AI error:", aiError)
    return errorResponse("Resona could not reach the language model. Please try again.", 502, true)
  }

  if (!responseText) {
    return errorResponse("Resona returned an empty reply. Please try again.", 502, true)
  }

  if (qoteData) {
    ResonanceLogger.log({
      timestamp: new Date().toISOString(),
      userPhase: qoteData.phase,
      resonaPhase: qoteData.phase,
      alignmentScore: qoteData.alignmentSource === "calculated" ? qoteData.alignment : null,
      flipPotential: qoteData.flipPotential,
      inputText: sanitizedMessage,
      outputText: responseText,
    })
  }

  return Response.json({
    response: responseText,
    source: "ai",
    model: MODEL_ID,
    mode,
    qoteData: qoteData ? sanitizeQOTE(qoteData, presenceOn) : null,
    rtpResponse,
    resonanceStats: lensOn ? getResonanceStats() : null,
    timestamp: new Date().toISOString(),
  })
}

export async function GET(request: Request) {
  const url = new URL(request.url)

  if (url.searchParams.get("action") === "analytics") {
    return Response.json({
      ...getResonanceStats(),
      recentLogs: ResonanceLogger.getRecentLogs(5),
      status: "QOTE lens active with RTP",
    })
  }

  return Response.json({
    status: "Resona QOTE API with RTP is active",
    version: "1.2.0",
    features: ["QOTE Lens", "Explicit Presence Mode", "Identity answers", "Resonance Logging", "RTP v1.0"],
    timestamp: new Date().toISOString(),
  })
}
